export const GET_INFO           = "GET_INFO";
export const FETCH_INFO_REQUEST = "FETCH_INFO_REQUEST";
export const FETCH_INFO_FAILURE = "FETCH_INFO_FAILURE";
export const FETCH_INFO_SUCCESS = "FETCH_INFO_SUCCESS";
export const GET_DOORBELL_OUT           = "GET_DOORBELL_OUT";
export const FETCH_DOORBELL_OUT_REQUEST = "FETCH_DOORBELL_OUT_REQUEST";
export const FETCH_DOORBELL_OUT_FAILURE = "FETCH_DOORBELL_OUT_FAILURE";
export const FETCH_DOORBELL_OUT_SUCCESS = "FETCH_DOORBELL_OUT_SUCCESS";
